[package]
name = "redo"
version = "0.30.1"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides undo-redo functionality with static dispatch and manual command merging."
documentation = "https://docs.rs/redo"
repository = "https://github.com/evenorog/redo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures", "rust-patterns"]
exclude = ["/.travis.yml"]
edition = "2018"

[dependencies]
bitflags = "1"
chrono = { version = "0.4.6", optional = true, features = ["serde"] }
colored = "1"
rustc-hash = "1"
serde = { version = "1", optional = true, features = ["derive"] }

[features]
default = ["std"]
std = []

[badges]
travis-ci = { repository = "evenorog/redo" }
maintenance = { status = "actively-developed" }
