[package]
name = "redo"
version = "0.8.1"
authors = ["evenorog <evenorog@gmail.com>"]
description = "An undo/redo library with static dispatch and manual command merging."
documentation = "https://docs.rs/redo"
repository = "https://github.com/evenorog/redo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures"]

[dependencies]
fnv = "1.0.5"
