[package]
name = "redo"
version = "0.27.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "An undo-redo library with static dispatch and manual command merging."
documentation = "https://docs.rs/redo"
repository = "https://github.com/evenorog/redo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures"]

[dependencies]
bitflags = "1"
chrono = { version = "0.4.6", optional = true, features = ["serde"] }
colored = "1"
fnv = "1"
serde = { version = "1", optional = true, features = ["derive"] }

[features]
default = ["chrono"]
